name: Run Python Script

on:
  push:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies

    - name: Remove Existing Chromedriver
      run: sudo rm /usr/local/bin/chromedriver || true

    - name: Download and Set up ChromeDriver
      run: |
        CHROMEDRIVER_VERSION="<<version>>"
        wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        mkdir -p $HOME/bin
        mv chromedriver $HOME/bin/
        rm chromedriver_linux64.zip
        echo "::add-path::$HOME/bin"

    - name: Run Python Script
      run: python ./tests/automateScript.py 
